# General defaults

prefix: "{{ provisioner.prefix | default(random.uuid) }}"

# Network defaults

timeout_network: 180

# Subnet defaults

enable_dhcp: True
dns_servers:
    - 208.67.222.222
    - 8.8.8.8

# Router defaults

router_name: router1

# Security group defaults

security_group_name: default
