---
- name: Generate Deployer output for Tester
  hosts: undercloud
  gather_facts: no
  become: yes
  become_user: "{{ installer.user.name }}"
  tasks:
      - name: "Workaround RHBZ#1357579 - non-default region=regionOne"
        shell: "crudini --set ~/tempest-deployer-input.conf identity region regionOne"
        when: installer.workarounds is defined and installer.workarounds.rhbz1357579 is defined

      - name: "Enable console logging: https://review.openstack.org/#/c/387445/"
        ini_file:
            dest: "~/tempest-deployer-input.conf"
            section: compute-feature-enabled
            option: console_output
            value: true

      - name: "Disable encrypted volume tests rhbz#1383377"
        ini_file:
            dest: "~/tempest-deployer-input.conf"
            section: compute-feature-enabled
            option: attach_encrypted_volume
            value: false

      - name: "Configure storage protocol when ceph: https://bugs.launchpad.net/tripleo/+bug/1634499"
        ini_file:
            dest: "~/tempest-deployer-input.conf"
            section: volume
            option: storage_protocol
            value: ceph
        when:  "installer.storage.backend.startswith('ceph')"

      - name: fetch deployer output for tester
        fetch:
            src: "~/{{ item.src }}"
            dest: "{{ inventory_dir }}/{{ item.dest }}"
            flat: yes
        with_items:
            - src:  "overcloudrc"
              dest: "keystonerc"
            - src:  "tempest-deployer-input.conf"
              dest: "tempest-deployer-input.conf"
