- name: Creating scale script.
  shell: "cp -pv ~/overcloud_deploy.sh ~/overcloud_scale.sh"

- name: change amount of scaled nodes
  replace:
      dest: "~/overcloud_scale.sh"
      regexp: '^(\s*)--{{ service }}-scale\s\d\s\\'
      replace: '\1--{{ service }}-scale {{ amount }} \\'

- name: change log file destination
  replace:
      dest: "~/overcloud_scale.sh"
      regexp: '^(\s*)--log-file.*'
      replace: '\1--log-file overcloud_scale.log'

- name: the scale overcloud script
  shell: "cat ~/overcloud_scale.sh"

- name: scaling overcloud
  shell: |
      source ~/stackrc
      bash ~/overcloud_scale.sh
  register: overcloud_scaling
  ignore_errors: yes

- name: print the last few lines of the output to spot failures
  shell: "tail -n60 overcloud_scale.log"

- fail: msg="Overcloud scailing failed... :("
  when: overcloud_scaling.rc != 0
