---
features:
  - |
    Allow to specify target hosts for collect-logs plugin.
    Now user can limit the list of servers from which IR should collect logs with
    the --hosts option::

            infrared collect-logs --hosts undercloud
