# The destination path for the venv
# venv_destination_path: ""

# We use the OpenStack upper-constraints file to help
# insulate us from problems with new releases of
# pypi-sourced dependencies when installing.
# We use the 'train' constraints for RHEL < 8 because it
# is the last OpenStack release that tests both py2 and py3.
# For RHEL >= 8 we use the 'master' constraints.
venv_constraints: "https://releases.openstack.org/constraints/upper/{{ (venv_python_version | int == 2) | ternary('train', 'master')"

# list of regexes to remove from the venv constraints before doing the install
venv_constraints_remove: []

# The distribution packages required to install the python packages
venv_distro_package_list:
  - gcc
  - "{{ (venv_python_version | int == 2) | ternary('python-devel', 'python3-devel') }}"

# The python packages to install into the venv
venv_pip_packages: []

# The python version that is standard on the host
venv_python_version: "{{ (ansible_distribution in ['CentOS', 'RedHat'] and ansible_distribution_major_version | int < 8) | ternary(2, 3) }}"

# Recreate the venv
venv_rebuild: no

# Add system-site-packages to the venv
venv_system_site_packages: no
