---
# This file is used to create OpenStack nova resources

#TODO(abregman): Enable 'create_flavors' when ansible 2.1 is out
#- name: Create flavors
#  os_nova_flavor:
#      cloud: "{{ provisioner.cloud | default(omit) }}"
#      name: "{{ prefix }}{{ item.value.nane | default(flavor_name) }}"
#      ram: "{{ item.value.ram | default(omit) }}"
#      disk: "{{ item.value.disk | default(omit) }}"
#      vcpus: "{{ item.value.vcpus | default(omit) }}"
#      state: present
#  register: flavors
#  with_dict: "{{ provisioner.flavors }}"
#  when: provisioner.flavors is defined

# This is needed for os_keypair as it uses public key
- name: Retrieve public key from private key
  shell: "ssh-keygen -y -f {{ provisioner.key.file }}"
  register: public_key_content

- name: Add keypair
  os_keypair:
      cloud: "{{ provisioner.cloud | default(omit) }}"
      name: "{{ prefix }}{{ provisioner.key.file | basename }}"
      public_key: "{{ public_key_content.stdout }}"
      state: present
  when: not provisioner.key.name

# This includes the tasks for instances and floating IPs creation
- include: "setup_nodes.yml"
  with_dict: "{{ provisioner.nodes }}"
