---
- name: Install plugin packages
  become: yes
  yum:
      name: "{{ item.value.package }}"
      state: present
  with_dict: "{{ test_suite.value.plugins | default({}) }}"

- name: install extra system requirements for tests
  become: yes
  yum:
    name: "{{ item.value.dependencies }}"
    state: present
  with_dict: "{{ plugins }}"
  when: item.value.dependencies is defined
