- block:
    - name: import swift facts
      set_fact:
          ceph_facts: "{{ lookup('file', '{{ inventory_dir }}/{{ hostvars[(groups.swift|first)].inventory_hostname }}') }}"

    # If you reached this stage, it means a user explicitely entered the storage flag therefore he wants at least 1 node
    - name: append the swift storage template line to the base overcloud deploy script
      lineinfile:
          dest: "~/overcloud_deploy.sh"
          line: '--swift-storage-scale {{ storage_nodes }} \'
      when: "templates.storage_add_scale | default('yes') == 'yes'"

    - name: append the swift storage template line to the base overcloud deploy script
      lineinfile:
          dest: "~/overcloud_deploy.sh"
          line: '--swift-storage-flavor {% if groups["swift"] is defined %}swift{% else %}baremetal{% endif %} \'
      when: "templates.storage_add_scale | default('yes') == 'yes'"

  when: installer.storage.external != "yes"
  vars:
      storage_nodes: "{{ (installer.storage.nodes == None) |ternary([1, groups['ceph'] |default([])|length] | max, installer.storage.nodes) }}"

- name: prepare swift storage template
  template:
      src: "storage/swift.yml.j2"
      dest: "{{ template_base }}/swift.yaml"
      mode: 0755

- name: append the storage swift custom template line to the base overcloud deploy script
  lineinfile:
      dest: "~/overcloud_deploy.sh"
      line: '-e {{ template_base }}/swift.yaml \'
