---
- name: Rally Scenarios - Post tasks
  hosts: tester
  become: yes
  any_errors_fatal: true
  tasks:
    - name: Create Output Directory
      file: path={{ tester.rally.outputdir }} state=directory

# TODO(yfried): fix relative link in index so they point to the right path and don't use gz files
#    - name: Create nice index
#      shell: "{{ tester.rally.path }}/bin/rally rally/ui/utils.py render tests/ci/rally-gate/index.mako >  {{ tester.rally.outputdir }}/index.html"
#      args:
#        creates: "{{ tester.rally.outputdir }}/index.html"
#        chdir: "{{ tester.rally.dir }}"

    - name: Create Report
      command: "{{ tester.rally.path }}/bin/rally task report --out {{ tester.rally.outputdir }}/results.html"
      args:
        creates: "{{ tester.rally.outputdir }}/results.html"

    - name: Create Report JUnit
      command: "{{ tester.rally.path }}/bin/rally task report --junit --out {{ tester.rally.outputdir }}/nosetests.xml"
      args:
        creates: "{{ tester.rally.outputdir }}/nosetests.xml"

    - name: JSON results
      shell: "{{ tester.rally.path }}/bin/rally task results | {{ tester.rally.path }}/bin/python -m json.tool > {{ tester.rally.outputdir }}/results.json"
      args:
        creates: "{{ tester.rally.outputdir }}/results.json"

    - name: Iteration Data
      shell: "{{ tester.rally.path }}/bin/rally task detailed > {{ tester.rally.outputdir }}/detailed.txt"
      args:
        creates: "{{ tester.rally.outputdir }}/detailed.txt"

    - name: Detatiled Iteration Data
      shell: "{{ tester.rally.path }}/bin/rally task detailed --iterations-data > {{ tester.rally.outputdir }}/detailed_with_iterations.txt"
      args:
        creates: "{{ tester.rally.outputdir }}/detailed_with_iterations.txt"

    - name: SLA Check
      shell: "{{ tester.rally.path }}/bin/rally task sla_check > {{ tester.rally.outputdir }}/sla.txt"
      args:
        creates: "{{ tester.rally.outputdir }}/sla.txt"
      ignore_errors: true

    - name: SLA Check JSON
      shell: "{{ tester.rally.path }}/bin/rally task sla_check --json > {{ tester.rally.outputdir }}/sla.json"
      args:
        creates: "{{ tester.rally.outputdir }}/sla.json"
      ignore_errors: true


# These need to be archived by Jenkins Somehow
    - name: Fetch Results
    # Assumes env has $WORKSPACE defined like in Jenkins
      fetch: src={{ item }} dest="{{ lookup('env','PWD') }}/" fail_on_missing=yes flat=yes
      with_items:
#        - "{{ tester.rally.outputdir }}/index.html"
        - "{{ tester.rally.outputdir }}/results.html"
        - "{{ tester.rally.outputdir }}/nosetests.xml"
        - "{{ tester.rally.outputdir }}/detailed.txt"
        - "{{ tester.rally.outputdir }}/detailed_with_iterations.txt"
        - "{{ tester.rally.outputdir }}/sla.txt"
        - "{{ tester.rally.outputdir }}/sla.json"
