---
# this role is supposed to be execuded on undercloud
# TODO(yfried): find a better method to load stackrc file
- block:
    - shell: "cat {{ undercloud_rc }} | grep AUTH_URL | cut -d '=' -f 2"
      register: oc_auth

    - shell: "echo {{ oc_auth.stdout }} | grep -P -o '(\\d+\\.\\d+\\.\\d+\\.\\d+)'"
      register: oc_auth_ip

    - shell: "cat {{ undercloud_rc }} | grep USERNAME | cut -d '=' -f 2"
      register: oc_username

    - shell: "cat {{ undercloud_rc }} | grep TENANT | cut -d '=' -f 2"
      register: oc_tenant

    - shell: "source {{ undercloud_rc }} && env | grep OS_PASSWORD | cut -d '=' -f 2"
      args:
          executable: /bin/bash
      register: oc_password

    - set_fact:
        oc_auth: "{{ oc_auth.stdout }}"
        oc_auth_ip: "{{ oc_auth_ip.stdout }}"
        oc_username: "{{ oc_username.stdout }}"
        oc_tenant: "{{ oc_tenant.stdout }}"
        oc_password: "{{ oc_password.stdout }}"
  vars:
    undercloud_rc: overcloudrc
