---
- name: switch selinux to permissive
  selinux: policy=targeted state=permissive

#this is required to have the 22 port free on haproxy VIP's
- name: setup ssh to listen on existing external IP
  lineinfile:
      dest: "/etc/ssh/sshd_config"
      line: "ListenAddress {{ hostvars[inventory_hostname].ansible_ssh_host }}"

- name: setup ssh for loadbalancer to listen on external VIP
  lineinfile:
      dest: "/etc/ssh/sshd_config"
      line: "ListenAddress {{ installer.loadbalancer.network.external.vip | ipaddr('address') }}"

- name: restart sshd service
  service:
      name: sshd
      state: restarted

- name: enable vlan kernel module
  lineinfile:
      dest: "/etc/sysconfig/modules/vlan.modules"
      state: present
      create: yes
      line: "exec /sbin/modprobe 8021q >/dev/null 2>&1"


- name: create VLAN interface for plain network
  template:
      src: vlan-plain.cfg.j2
      dest: /etc/sysconfig/network-scripts/ifcfg-{{ installer.loadbalancer.network.oc_interface }}
  when: installer.loadbalancer.network.plain is defined

- name: create IPV4 VLAN interface for external network as alias
  template:
      src: vlan-external.cfg.j2
      dest: /etc/sysconfig/network-scripts/ifcfg-{{ installer.loadbalancer.network.ex_interface }}:0
  when: installer.loadbalancer.network.external is defined and installer.network.protocol == 'ipv4'

- name: create IPV6 VLAN interface for external network
  lineinfile:
      dest: /etc/sysconfig/network-scripts/ifcfg-{{ installer.loadbalancer.network.ex_interface }}
      line: "{{ item }}"
  with_items:
      - "IPV6_AUTOCONF=no"
      - "IPV6ADDR={{ installer.loadbalancer.network.external.vip | ipaddr('address') }}"
      - "IPV6PREFIX={{ installer.loadbalancer.network.external.vip | ipaddr('prefix') }}"
  when: installer.loadbalancer.network.external is defined and installer.network.protocol == 'ipv6'


- name: create VLAN interface for internal_api network
  template:
      src: vlan-internal_api.cfg.j2
      dest: /etc/sysconfig/network-scripts/ifcfg-{{ installer.loadbalancer.network.oc_interface }}.{{ installer.loadbalancer.network.internal_api.vlanid }}
  when: installer.loadbalancer.network.internal_api is defined

- name: create VLAN interface for storage network
  template:
      src: vlan-storage.cfg.j2
      dest: /etc/sysconfig/network-scripts/ifcfg-{{ installer.loadbalancer.network.oc_interface }}.{{ installer.loadbalancer.network.storage.vlanid }}
  when: installer.loadbalancer.network.storage is defined

- name: create VLAN interface for storage_mgmnt network
  template:
      src: vlan-storage_mgmt.cfg.j2
      dest: /etc/sysconfig/network-scripts/ifcfg-{{ installer.loadbalancer.network.oc_interface }}.{{ installer.loadbalancer.network.storage_mgmnt.vlanid }}
  when: installer.loadbalancer.network.storage_mgmnt is defined

- name: create VLAN interface for tenant network
  template:
      src: vlan-tenant.cfg.j2
      dest: /etc/sysconfig/network-scripts/ifcfg-{{ installer.loadbalancer.network.oc_interface }}.{{ installer.loadbalancer.network.tenant.vlanid }}
  when: installer.loadbalancer.network.tenant is defined

- name: update all packages
  yum: name=* state=latest

- name: install haproxy service
  yum: name=haproxy state=present

- name: copy haproxy configuration file
  template:
      src: haproxy.cfg.j2
      dest: /etc/haproxy/haproxy.cfg

- name: start haproxy service
  service:
      name: haproxy
      state: started
      enabled: yes

- name: reboot the loadbalancer
  command: "virsh reboot {{ inventory_hostname }}"
  delegate_to: virthost
  when: "'virthost' in groups"

- name: reboot the loadbalancer
  shell: "sleep 2 && shutdown -r now"
  async: 1
  poll: 0
  ignore_errors: true
  when: "'virthost' not in groups"

- name: Waiting for the loadbalancer to be available
  delegate_to: localhost
  wait_for:
      host: "{{ hostvars[inventory_hostname].ansible_ssh_host }}"
      timeout: 120

- name: Make sure haproxy service is started
  service:
      name: haproxy
      state: started
      enabled: yes
