---
- name: Use beaker to provision/release the machine
  hosts: localhost
  tasks:
    - name: Provisioning the machine
      beaker_provisioner:
          url: "{{ provisioner.url }}"
          username: "{{ provisioner.user }}"
          password: "{{ provisioner.password }}"
          host: "{{ provisioner.host.address }}"
          action: "provision"
          distro_tree_id: "{{ provisioner.image.distro.trees.id }}"
          web_service: "{{ provisioner.web.service }}"
          ca_cert: "{{ provisioner.ca.cert | default(omit) }}"

    - name: wait for ssh
      wait_for:
          port: 22
          host: "{{ provisioner.host.address }}"
          search_regex: OpenSSH
      delay: 10

- name: Add the host to our inventory
  hosts: localhost
  tasks:
    - name: Add the host to host list
      add_host:
          name: "{{ provisioner.host.address }}"
          # TODO: Move tester and even undercloud grouping to later phases in future
          groups: "baremetal,undercloud,tester"
          ansible_ssh_host: "{{ provisioner.host.address }}"
          ansible_ssh_user: "{{ provisioner.host.user }}"
          ansible_ssh_pass: "{{ provisioner.host.password | default(omit) }}"
          ansible_ssh_private_key_file: "{{ provisioner.host.key | default(omit) }}"

- name: Add the host to our inventory
  hosts: baremetal
  gather_facts: no
  tasks:

    - name: Inject our public key to the autorized users
      connection: paramiko
      authorized_key:
          user: "{{ provisioner.host.user }}"
          key: "{{ lookup('file', '%s/rhos-jenkins.pub' % inventory_dir) }}"
      when: provisioner.host.password is defined

    - name: Add our SSH key to the host
      add_host:
          name: "{{ provisioner.host.address }}"
          ansible_ssh_pass: None
          ansible_ssh_private_key_file: "{{ (provisioner.host.key == None) | ternary('~/.ssh/id_rsa', provisioner.host.key) }}"
      when: provisioner.host.password is defined