subscriptions:
    common:
        - rhel-7-server-rpms
        - rhel-7-server-extras-rpms
        - rhel-7-server-rh-common-rpms
    14:
        - rhel-ha-for-rhel-7-server-rpms
        - rhel-7-server-openstack-14-rpms
    13:
        - rhel-ha-for-rhel-7-server-rpms
        - rhel-7-server-openstack-13-rpms
    12:
        - rhel-ha-for-rhel-7-server-rpms
        - rhel-7-server-openstack-12-rpms
    11:
        - rhel-ha-for-rhel-7-server-rpms
        - rhel-7-server-openstack-11-rpms
    10:
        - rhel-ha-for-rhel-7-server-rpms
        - rhel-7-server-openstack-10-rpms
    9:
        - rhel-7-server-openstack-9-rpms
        - rhel-7-server-openstack-9-director-rpms
    8:
        - rhel-7-server-openstack-8-rpms
        - rhel-7-server-openstack-8-director-rpms
    7:
        - rhel-7-server-openstack-7.0-rpms
        - rhel-7-server-openstack-7.0-director-rpms
cdn_skip_openstack_repos: "{{ skip_release|default(false) }}"
