---
- include_tasks: validate_overcloud.yml

- block:
  - name: Assign dns as freeipa node to ctrlplane-subnet
    shell: |
        source {{ freeipa_undercloud_rc }}
        openstack subnet set ctlplane-subnet --dns-nameserver {{ freeipa_node_ipv4_address }}
    register: subnet_cmd_out
    failed_when: "subnet_cmd_out.rc != 0 and 'Duplicate nameserver' not in subnet_cmd_out.stderr"

  - name: Read deployment network configuration
    command: "cat {{ freeipa_network_environment_file }}"
    register: network_template_out

  - name: Load deployment network configuration as YAML
    set_fact:
        network_template: "{{ network_template_out.stdout | from_yaml }}"

  - name: Assign dns as freeipa node to network-environment
    lineinfile:
        dest: "{{ freeipa_network_environment_file }}"
        regexp: "- {{ network_template.parameter_defaults.DnsServers|first }}"
        line: "    - {{ freeipa_node_ipaddress }}"

  # TODO: figure out how to do this correctly
  - name: Assign dns search domains when domains do not match
    lineinfile:
        dest: "{{ freeipa_network_environment_file }}"
        regexp: "- {{ network_template.parameter_defaults.DnsSearchDomains|first }}"
        line: "    - [ {{ freeipa_clloud_domain }}, {{ freeipa_domain }} ]"
    when: "{{ freeipa_domain }} != {{ freeipa_cloud_domain }}"

  - name: Read deployment network configuration for ipv6
    command: "cat {{ freeipa_network_environment_v6_file }}"
    register: network_template_v6_out
    when: freeipa_network_protocol != 'ipv4'

  - name: Load deployment network configuration as YAML for ipv6
    set_fact:
        network_template_v6: "{{ network_template_v6_out.stdout | from_yaml }}"
    when: freeipa_network_protocol != 'ipv4'

  - name: Assign dns as freeipa node to network-environment-v6
    lineinfile:
        dest: "{{ freeipa_network_environment_v6_file }}"
        regexp: "- {{ network_template_v6.parameter_defaults.DnsServers|first }}"
        line: "    - {{ freeipa_node_ipaddress }}"
    when: freeipa_network_protocol != 'ipv4'
  delegate_to: "{{ freeipa_undercloud_node }}"

