# omit_groups provide option to remove list of groups during inventory file creation. Host that are part
# of the groups, will be also fully removed.
omit_groups: []

# omit_hosts provide option to remove list of hosts during inventory file creation.
omit_hosts: []

# inventory_file_name provide option for overwrite default value for inventory file name. "hosts" file is created from
# this file.
inventory_file_name: 'hosts-updated'
