---
- name: Install windowmanager
  yum: name=metacity state=present
  become: yes

- name: create windowmanager service
  template:
    src="{{service_name}}.j2"
    dest="/etc/systemd/system/{{service_name}}"
    owner=root group=root mode=0755
  become: yes

- name: reload systemd
  command: systemctl daemon-reload
  become: yes

- name: start windowmanager service
  service: name={{service_name}} state=restarted enabled=yes
  become: yes
