- name: prepare the network isolation
  template:
      src: "isolation.yml.j2"
      dest: "{{ installer.overcloud.template_base }}/isolation_params.yml"

- name: append our params to the network isolation file
  shell: "cat {{ installer.overcloud.template_base }}/isolation_params.yml >> {{ installer.overcloud.template_base }}/{{ installer.overcloud.network.template.file }}"

- name: append the network isolation template line to the base overcloud deploy script
  lineinfile:
      dest: "~/overcloud_deploy.sh"
      line: '                       -e {{ installer.overcloud.template_base }}/{{ installer.overcloud.network.template.file }} \\'

- name: append the net-single-nic-vlans template line base overcloud deploy script
  lineinfile:
      dest: "~/overcloud_deploy.sh"
      line: '                       -e {{ installer.overcloud.template_base }}/{{ installer.overcloud.network.isolation.file }} \\'

- name: add port to br-ctlplane for ipv6 over vlan support
  shell: "sudo ovs-vsctl add-port br-ctlplane vlan{{ installer.overcloud.network.template.parameter_defaults.ExternalNetworkVlanID }} tag={{ installer.overcloud.network.template.parameter_defaults.ExternalNetworkVlanID }} -- set interface vlan{{ installer.overcloud.network.template.parameter_defaults.ExternalNetworkVlanID }} type=internal"
  when: installer.overcloud.network.backend == 'vlan'

- name: add the ipv6 address
  shell: "sudo ip l set dev vlan{{ installer.overcloud.network.template.parameter_defaults.ExternalNetworkVlanID }} up; sudo ip addr add {{ installer.overcloud.network.template.parameter_defaults.ExternalInterfaceDefaultRoute }}/64 dev vlan{{ installer.overcloud.network.template.parameter_defaults.ExternalNetworkVlanID }}"
  when: installer.overcloud.network.backend == 'vlan'
