rr_distro_version: "{{ ansible_distribution_version }}"
rr_target_directory: /etc/yum.repos.d
# don't install rhos-release. Just if installed outside of IR, default - install
rr_skip_install_if_present: false
rr_discover_build: no
default_skip_remove_repos: ['/etc/yum.repos.d/patched_rpms.repo']
