---
- name: Register the host to Red Hat account
  include_tasks: register_cdn.yml
  # no need to register if machine already subscribed
  when: "cdn_args_file != ''"

# unregister repos and register back if no activation-key is used.
# if activation-key is used, the env will be automatically attached
# and subscribed to the repos assigned to the activation-key
- block:
    - name: unregister from all repos
      command: subscription-manager repos --disable=*
      failed_when: (unregister_repos.rc != 0 and "'*' does not match a valid repository ID." not in unregister_repos.stdout)
      register: unregister_repos
      become: true

    - name: register to openstack repos
      vars:
          repo_version: "{{ (install_version if install_version is defined else openstack_release)|string }}"
          repo_list: "{{ (subscriptions.common_8 if (repo_version|int) >= 15 else subscriptions.common_7) + (subscriptions[(repo_version|float)] if not cdn_skip_openstack_repos | default(false) else []) + (subscriptions.ceph_4 if install.storage is defined and install.storage.backend is defined and install.storage.backend == 'ceph' else []) }}"
          modified_list: "{{ repo_list | map('regex_replace', '^(.*)$', '--enable=\\1') | join(' ') }}"
      command: "subscription-manager repos {{ modified_list }}"
      become: true
      # running also if subscriptions are defined to avoid job breakages.

    - name: Set correct modules for OSP > 16
      become: true
      vars:
        repo_version: "{{ (install_version if install_version is defined else openstack_release)|string }}"
        module_list: "{{ dnf_modules[(repo_version|float)] }}"
        modules_list_disabled: "{{ module_list.disabled | join(' ') }}"
        modules_list_enabled: "{{ module_list.enabled | join(' ') }}"
      block:
      - command: 'dnf module disable {{ modules_list_disabled }} -y'
      - command: 'dnf module enable {{ modules_list_enabled }} -y'
      when: (install_version if install_version is defined else openstack_release)|float > 16

  when: (cdn_args_file != '' and cdn_creds.activationkey is undefined) or (subscriptions is defined and subscriptions|length > 0 )

- name: refresh yum cache
  package:
      name: kernel
      state: present
      update_cache: yes
  become: true

- name: repolist
  command: "yum -v repolist"
  become: true
