- vars:
      installer_options:
          ospd:
              orchestration.stack_owner_role: heat_stack_owner
              identity.region: regionOne
          packstack: {}

      openstack_config_options: "{{ installer_options.get(openstack_installer_type, {}) }}"
      config_options: "{{ openstack_config_options | combine(tester.get('config', {}).get('options', {})) }}"
  block:
      - name: check if deployer file is present
        stat:
            path: "{{ deployer_input }}"
        register: deployer_input_stat

      - name: run tempest configuration tool
        shell: |
            source .venv/bin/activate
            source ~/keystonerc
            tools/config_tempest.py \
                  {% if deployer_input_stat.stat.exists %}
                  --deployer-input {{ deployer_input }} \
                  {% endif %}
                  --debug \
                  --create \
                  --image {{ tester.base.image }} \
                  image.http_image  {{ tester.base.image }} \
                  scenario.img_file {{ tester.base.image | basename }} \
                  identity.uri $OS_AUTH_URL \
                  identity.admin_password $OS_PASSWORD \
                  scenario.img_dir ~/{{ tester.dir }}/etc \
                  {# config options #}
                  {% for name,value in config_options.iteritems() %}
                  {{name}} {{value}} \
                  {% endfor %}
                  {# insert test suite config options #}
                  {% for suite_name,suite_params in tester.tests.iteritems() %}
                  {% for name, value in suite_params.get('config_options', {}).iteritems() %}
                  {{name}} {{value}} \
                  {% endfor %}
                  {% endfor %}
                  --out ~/{{ tester.dir }}/etc/tempest.conf
        args:
            chdir: "{{ tester.dir }}"
