---
- name: Install required packages
  hosts: tester
  gather_facts: no
  become: no
  any_errors_fatal: true
  tasks:
      # test-specific packages
      - yum: name="{{ item }}" state=present
        with_items: "{{ tester.component.packages }}"

      # requirements of Ansible git modules
      - yum: name=git state=present

      - yum: name=python-virtualenv state=present
        when: "tester.component.pip_packages is defined and tester.component.pip_packages|length > 0"

- name: "Install pip if it's needed"
  hosts: tester
  gather_facts: yes
  become: no
  tasks:
    - command: "easy_install pip"
      when: "ansible_distribution in ['RedHat', 'CentOS'] and tester.component.pip_packages|default([])|length > 0"

- name: Prepare repository with tests
  hosts: tester
  become: yes
  become_user: "{{ installer.user.name }}"
  gather_facts: no
  any_errors_fatal: true
  tasks:
      - name: Clone repo with integration tests
        git:
            repo: "{{ tester.git.repo }}"
            accept_hostkey: true
            refspec: "{{ tester.git.revision | default(omit) }}"
            version: "{{ tester.git.version | default('FETCH_HEAD') }}"
            dest: "~/{{ tester.component.dir }}"
            force: yes
        register: tests_repo
      - command: chdir=~/{{ tester.component.dir }} git log -1 --pretty=format:%h
        register: tests_repo_version
      - debug: "msg='Build mark: int_test={{ tests_repo_version.stdout }}'"
      - name: Workaround for version conflict of setuptools
        pip: name="setuptools" version="24.0.3" virtualenv="~/{{ tester.component.venv_dir }}"
        when: "tester.component.pip_packages is defined and tester.component.pip_packages|length > 0"

      - name: Install pip test requirements
        pip: name="{{ item }}" virtualenv="~/{{ tester.component.venv_dir }}"
        with_items: "{{ tester.component.pip_packages }}"
        when: "tester.component.pip_packages is defined and tester.component.pip_packages|length > 0"

- name: Prepare the environment (users and tenant)
  hosts: undercloud
  become: yes
  become_user: "{{ installer.user.name }}"
  gather_facts: no
  any_errors_fatal: true
  roles:
      - openstack/ensure_shade
      - openstack/create_users

- include: "{{ tester.component.name }}/pre.yml"
