---
- name: install libguestfs-tools to get virt-customize
  become: yes
  yum:
      name: libguestfs-tools
      state: present

- name: tmp repos.d for overcloud
  file:
      name: "{{ tmp_oc_repos_dir }}"
      state: directory

# TODO(psedlak): use installer/rhos-release / mirror urls (do we want it here?)
- name: "create overcloud build's repos locally"
  rhos_release:
      state: install
      core_version: "{{ (installer.product.core.version is defined and installer.product.core.version) | ternary(installer.product.core.version, installer.product.version) }}"
      core_build_date: "{{ installer.product.core.build }}"
      target_directory: "{{ tmp_oc_repos_dir }}"
  register: command_result
  until: command_result.stderr.find('Connection reset by peer') == -1
  retries: 40
  delay: 5

- name: push core repos to overcloud image
  shell: "virt-copy-in -a {{ overcloud_image_file }} {{ tmp_oc_repos_dir }} /etc/"

- name: Install packages in overcloud image
  shell: "virt-customize -a {{ overcloud_image_file }} --install {{ installer.images.packages }}"
  when: installer.images['update'] in ['yes', 'verbose'] or installer.images.packages|default(None) != None

- name: update overcloud core bits to build's latest
  shell: "virt-customize {% if installer.images['update'] == 'verbose' %}-v{% endif %} -a {{ overcloud_image_file }} --update --selinux-relabel"
