---
- name: Prepare NetApp storage template
  template:
      src: "netapp.yml.j2"
      dest: "{{ installer.overcloud.template_base }}/custom-netapp.yml"
      mode: 0755

- name: Append the storage NetApp custom template line to the base overcloud deploy script
  lineinfile:
      dest: "~/overcloud_deploy.sh"
      line: '                       -e {{ installer.overcloud.template_base }}/custom-netapp.yml \'
