# Default role parameters
ospd_version: 8
work_dir: "~/overcloud_images"
dib_dir: '/etc/yum.repos.d'
distro_type: 'rhel7'
rhel_version_full: '7.2'
ospd_pin: 'latest'

# Mandatory role parameters
base_image_url: 'UNDEFINED'
rhos_release_rpm_link: 'UNDEFINED'
upload_to: 'none'
storage_server: 'UNDEFINED'
storage_path: 'UNDEFINED'
storage_ssh_key: 'UNDEFINED'
storage_user: 'UNDEFINED'
