- name: Installing the undercloud
  tags: undercloud_init
  hosts: undercloud
  become: yes
  any_errors_fatal: true
  roles:
      - role: installer/rhos-release
        rr_rpm_url: "{{ installer.product.rpm }}"
        director_version: "{{ installer.product.version }}"
        director_build: "{{ installer.product.build }}"
        core_version: "{{ (installer.product.core.version is defined and installer.product.core.version) | ternary(installer.product.core.version, installer.product.version) }}"
        core_build: "{{ installer.product.core.build }}"
        rr_distro_version: "{{ hostvars[groups.undercloud[0]].ansible_distribution_version }}"
        mirror: "{{ installer.mirror | default(omit) }}"

        when: installer.product.version|openstack_distribution == 'OSP'

      - role: installer/rdo-release
        product_version: "{{ installer.product.version }}"
        when: installer.product.version|openstack_distribution == 'RDO'

  tasks:
      - name: prepare the machine for undercloud deployment
        include: setup.yml

      - name: check if undercloud.conf is under the deployment folder
        stat:
            path: "{{ installer.deployment.files.rstrip('/') }}/undercloud.conf"
        delegate_to: localhost
        register: undercloud_conf

      - name: copy our configuration if provided by the user
        vars:
            local_src: "{%- if installer.undercloud|default('') and installer.undercloud.config|default('') and installer.undercloud.config.file|default('') -%}
                {{ installer.undercloud.config.file }}
                {%- elif undercloud_conf.stat.exists -%}
                {{ undercloud_conf.stat.path }}
                {%- elif 'virthost' in groups.all -%}
                templates/undercloud.conf
                {%- else -%}
                False
                {%- endif -%}"
            deafult_conf: /usr/share/instack-undercloud/undercloud.conf.sample
        copy:
            remote_src: "{{ not local_src }}"
            src: "{{ local_src | ternary(local_src, deafult_conf)}}"
            dest: "/home/{{ installer.user.name }}/undercloud.conf"
            owner: "{{ installer.user.name }}"
            group: "{{ installer.user.name }}"
            mode: 0755
            force: yes

      - name: enable undercloud-ssl
        include: ssl.yml
        when: installer.undercloud.ssl == 'yes'

      - name: override values in undercloud conf
        ini_file:
            dest: "/home/{{ installer.user.name }}/undercloud.conf"
            section: "{{ item.key.split('.')[0] }}"
            option: "{{ item.key.split('.')[1] }}"
            value: "{{ item.value }}"
        with_dict: "{{ ((installer.undercloud|default({})).config|default({})).options|default({}) }}"

      - name: create the base undercloud deploy script
        template:
            src: "undercloud_deploy.sh.j2"
            dest: "/home/{{ installer.user.name }}/undercloud_deploy.sh"
            mode: 0755

      - name: the create undercloud script
        shell: "cat /home/{{ installer.user.name }}/undercloud_deploy.sh"
        tags: undercloud_deploy
