- name: Introspect our machines
  hosts: undercloud
  gather_facts: no
  any_errors_fatal: true
  vars:
      - undercloud_provision_cidr: "{{ ansible_br_ctlplane.ipv4.network }}/{{ ansible_br_ctlplane.ipv4.netmask }}"
      - custom_instack: "{{ (installer.instackenv|default({})).file | default('') }}"
  tasks:
      - name: "Set selinux state on undercloud after install"
        tags: ironic
        selinux:
            policy: "targeted"
            state: "{{ installer.selinux | default('enforcing') }}"
        become: yes

      # User provided file overwrites everything
      - name: check if instackenv is under the deployment folder
        tags: ironic
        stat:
            path: "{{ installer.deployment.files.rstrip('/') }}/instackenv.json"
        delegate_to: localhost
        become: no
        register: old_custom_instack
        when: custom_instack == ''
        changed_when: custom_instack == ''

      - set_fact:
            old_custom_instack_path: "{{ old_custom_instack.stat.path }}"
        when: old_custom_instack|changed and old_custom_instack.stat.exists != false
        tags: ironic

      - name: copy instackenv if provided by the user
        tags: ironic
        copy:
            src: "{{ (custom_instack != '') | ternary(custom_instack, old_custom_instack_path) }}"
            dest: "/home/{{ installer.user.name }}/{{ custom_instack | basename }}"
        when: custom_instack != '' or old_custom_instack.stat.exists
        register: inject_instackenv

      - set_fact:
            inject_instackenv_name: "{{ inject_instackenv.dest|basename }}"
        when: inject_instackenv|changed
        tags: ironic

      - name: verify that instackenv json file exists
        tags: ironic
        vars:
            target: "{{ (inject_instackenv|changed) | ternary((inject_instackenv_name), 'instackenv.json') }}"

        stat:
            path: "/home/{{ installer.user.name }}/{{ target }}"
        register: instack_file_path

      - set_fact:
            instack_file: "{{ instack_file_path.stat.path }}"
        when: instack_file_path.stat.exists
        tags: ironic

      - fail:
            msg: "instackenv file is missing"
        when: not instack_file_path.stat.exists
        tags: ironic

      - name: register our hosts to instack
        tags: ironic
        shell: "source ~/stackrc; openstack baremetal import --json {{ instack_file }}"

      - name: assign the kernel and ramdisk before introspection begins
        tags: ironic
        shell: "source ~/stackrc; openstack baremetal configure boot"

      - name: start node introspection
        shell: |  
            source ~/stackrc
            openstack baremetal introspection bulk start
        register: introspection_status
        retries: 5
        delay: 10
        until: introspection_status.rc == 0
        #ignore_errors: yes
