---
- name: Prepare templates
  hosts: undercloud
  become: yes
  become_user: "{{ installer.user.name }}"
  gather_facts: no
  pre_tasks:
      - fail:
            msg: "Stopping before editing of the overcloud templates per user request"
        when: break is defined and break == "before_editing_overcloud_templates"

      - name: create the template folder for customization
        shell: "mkdir -p {{ installer.overcloud.template_base }}"

      - name: create the base overcloud deploy script
        template:
            src: "templates/overcloud_deploy.sh.j2"
            dest: "~/overcloud_deploy.sh"
            mode: 0755
  roles:
      - {role: "installer/ospd/overcloud/storage/ceph/", when: installer.overcloud.storage.backend is defined and installer.overcloud.storage.backend == "ceph"}
      - {role: "installer/ospd/overcloud/storage/netapp/", when: installer.overcloud.storage.backend is defined and installer.overcloud.storage.backend == "netapp"}
      - {role: "installer/ospd/overcloud/network/isolation/{{ installer.overcloud.network.isolation.type }}/", when: installer.overcloud.network.isolation.enable == "yes"}
      - {role: "installer/ospd/overcloud/ssl/", when: installer.overcloud.use_ssl == "yes"}
      - {role: "installer/ospd/overcloud/loadbalancer/deploy/", when: provisioner.topology.nodes.loadbalancer is defined}

- name: Install the overcloud
  hosts: undercloud
  become: yes
  become_user: "{{ installer.user.name }}"
  gather_facts: no
  tasks:
      - name: append the invocation line to the base overcloud deploy script
        lineinfile:
            dest: "~/overcloud_deploy.sh"
            line: "                       --log-file overcloud_deployment_{{ 100 | random }}.log &> overcloud_install.log"

      - name: the create overcloud script
        shell: "cat ~/overcloud_deploy.sh"

      - fail:
            msg: "Stopping before the overcloud installation per user request"
        when: break is defined and break == "before_overcloud_installation"

      - name: execute the overcloud deploy script (should take ~30 minutes :) )
        shell: "bash ~/overcloud_deploy.sh"
        register: overcloud_deploy
        ignore_errors: yes

      - name: print the last few lines of the output to spot failures
        shell: "tail -n30 overcloud_install.log"

      - fail: msg="Overcloud deployment failed... :("
        when: overcloud_deploy.rc != 0