---
- name: create VLAN interface for internal_api network
  become_user: root
  template:
      src: vlan-internal_api.cfg.j2
      dest: "/etc/sysconfig/network-scripts/ifcfg-{{ installer.loadbalancer.network.undercloud.oc_interface }}.{{ installer.loadbalancer.network.internal_api.vlanid }}"
  when: installer.loadbalancer.network.internal_api is defined

- name: Start internal_api interface
  shell: "sudo /usr/sbin/ifup {{ installer.loadbalancer.network.undercloud.oc_interface }}.{{ installer.loadbalancer.network.internal_api.vlanid }}"

- name: copy the loadbalancer template
  template:
      src: "external-lb.yaml.j2"
      dest: "~/external-lb.yaml"

- name: append the External LB template line to the base overcloud deploy script
  lineinfile:
      dest: "~/overcloud_deploy.sh"
      line: '-e /usr/share/openstack-tripleo-heat-templates/environments/external-loadbalancer-vip{{ (installer.network.protocol == "ipv6") | ternary("-v6","") }}.yaml \'

- name: append External LB config to the base overcloud deply script
  lineinfile:
      dest: "~/overcloud_deploy.sh"
      line: '-e ~/external-lb.yaml \'
