---
- include: provisioner/{{ provisioner.type }}/cleanup.yml

- name: restore inventory file with just localhost
  hosts: localhost
  tasks:
    - name: Unlink hosts file
      file:
        dest: "{{ lookup('env', 'PWD') }}/hosts"
        state: link
        src: "{{ lookup('env', 'PWD') }}/local_hosts"
